config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users, only: %i[index new create show]
  resources :posts do
    collection do
      get 'search'
      # ネストすることでpostsコントローラーのsearchアクションを取得する。
      # collectionによりposts全体を対象としているため、idを必要としないパスとなる。
    end
    resources :comments, shallow: true
  end
  # shallowオプションについてはRailsガイド'ルーティング'の2.7.2を参考に記述
  # comment_idをparamsに持つアクション(show/edit/update/destroy)についてURLを短くすることができる。
  # (urlを短くしても一意性を確保出来ている)

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  namespace :mypage do
    resource :account, only: %i[edit update]
  end
  # namespaceでコントローラーをグループ化する。(今はaccountsコントローラーのみだが、今後増えることを想定した実装となる)
  # この記述で、/"namespace名"/"コントローラー名"というパスを得る。
  # 自分自身に対しての処理のため単一resourceメソッドを用いた。

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 255 }
  # bodyは空入力を許可しない。文字数にも制約をつけた。
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: %i[create edit update destroy]
  # ログイン時のみ許可

  def create
    @comment = current_user.comments.create(comment_params)
    # current_userを指定してコメントのcreateを実行する
  end

  # editはshallowの対象
  def edit
    @comment = current_user.comments.find(params[:id])
  end

  # updateはshallowの対象
  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_update_params)
  end

  # updateはshallowの対象
  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
    # post_idをcommentに紐づけて保存出来るようにする
    # user_idについてはcurrent_user.comments.create(comment_params)で取得できている
  end

  def comment_update_params
    params.require(:comment).permit(:body)
    # updateするものはbodyのみ。それ以外の項目が変更されることは基本的にないため許可する必要もない
  end
end

app/views/comments/_comment.html.slim
div id="comment-#{comment.id}"
  .row.no-gutters
    .col-2
      = image_tag comment.user.avatar.url, size: '40x40', class: 'rounded-circle'
    .col-9
      span.font-weight-bold.pr-1
        = comment.user.username
      = comment.body
    .col-1
      / ログイン時かつ自身の投稿の場合は編集削除ができる分岐を導入する
      - if logged_in? && comment.user_id == current_user.id
        = link_to comment_path(comment), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
          = icon 'far', 'trash-alt', class: 'fa-sm'
        = link_to edit_comment_path(comment), remote: true do
          = icon 'far', 'edit', class: 'fa-sm'
          / remote: true という記述はjs形式でリクエストを送信するためのもの。非同期化のため
          / 対応するjsファイルを探しにいく
  hr

app/views/comments/_comments.html.slim
.comments-box
  = render comments

/ 投稿(post)のshowページから@commentsを受け取っている。
/ 受け取った@commentsをさらに"comments"として部分テンプレート先へ渡している
/ 以下の省略記法となる
/ render partial: 'comment', collection: comments ⇦実態は@commentsが入っているというイメージ
/ すなわち部分テンプレート先は"_comment.html.slim"となり、
/ 部分テンプレート内で使う変数は、commentsから取り出し"comment"として扱う。

app/views/comments/_modal_form.html.slim
.modal#comment-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title コメント編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×

      / 以下モーダルのフォーム部分
      .modal-body
        = form_with model: comment, class: 'd-flex mb-0 flex-nowrap justify-content-between', remote: true do |f|
          = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
          = f.submit '投稿', class: 'btn btn-primary btn-raised'
      / showページ内のコメント新規登録フォームとさほど変わらず。
      / shallowオプションが適用されているので、postモデルを経由する必要はない

app/views/comments/create.js.slim
/ 保存出来なかった場合にアラートを出す
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  | $('.comments-box').prepend("#{j render('comments/comment', comment: @comment)}");
  | $('.input-comment-body').val('');
  / jsのprependメソッドを使い要素内の先頭にテキストを追加する。[対象要素.prepned(追加したい文字列)]
  / ruby部分の「j render〜〜」のjは、RailsActionView::Helperのescape_javascriptメソッド。
  / rubyで書いた構文をjs形式へ変換してくれる。
  / jsのvalメソッドを使用しテキストフィールドの部分を空にする。要素の中身を''で囲ったものに変更している。

app/views/comments/destroy.js.slim
| $('#comment-#{@comment.id}').remove()
/ jsのremoveメソッドを使用し、指定の要素を削除している

app/views/comments/edit.js.slim
| $("#modal-container").html("#{j (render 'modal_form', comment: @comment)}");
| $("#comment-edit-modal").modal('show');

/ 1行目で、comments/_modal_formのファイルを"#modal-container"にhtml形式で挿入している。
/ 2行目で、jsのmodalメソッドを使用し、"#comment-edit-modal"以下をmodalとして表示。
/ modal('show')でmodalを開くことが出来る。

app/views/comments/update.js.slim
/ 更新出来なかった場合にアラートを出す
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  | $("#comment-#{@comment.id}").html("#{j render('comments/comment', comment: @comment)}");
  | $("#comment-edit-modal").modal('hide');
/ 対象のcomment_idの内容を更新したものに差し替える(htmlメソッドで文字列を上書きするイメージ)
/ 更新が終わったのでmodal('hide')でedit.js.slimにて開いたモーダルを閉じる処理を行う