config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users, only: %i[index new create show]
  resources :posts do
    collection do
      get 'search'
      # ネストすることでpostsコントローラーのsearchアクションを取得する。
      # collectionによりposts全体を対象としているため、idを必要としないパスとなる。
    end
    resources :comments, shallow: true
  end
  # shallowオプションについてはRailsガイド'ルーティング'の2.7.2を参考に記述
  # comment_idをparamsに持つアクション(show/edit/update/destroy)についてURLを短くすることができる。
  # (urlを短くしても一意性を確保出来ている)

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  namespace :mypage do
    resource :account, only: %i[edit update]
  end
  # namespaceでコントローラーをグループ化する。(今はaccountsコントローラーのみだが、今後増えることを想定した実装となる)
  # この記述で、/"namespace名"/"コントローラー名"というパスを得る。
  # 自分自身に対しての処理のため単一resourceメソッドを用いた。

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  # userは複数のpostを持つというアソシエーション
  # userとpost両方ともアソシエーションを記入する必要がある

  has_many :comments, dependent: :destroy
  # userは複数のcommentを持つ
  # dependent: :destroyを設定することで、userを削除したときアソシエーション先（この場合はpost・comment）にもdestroyアクションを実行することができる（削除できる）

  # 【いいね機能に関するアソシエーション】
  has_many :likes, dependent: :destroy
  # ↓いいねをしたpostを取得するために記述。ActiveRecordの関連付け。correctionを取得する。
  has_many :like_posts, through: :likes, source: :post
  # throughオプションは指定したテーブルを経由して関連先のデータを取得できるようになるオプション。
  # "has_many :like_posts, through: :likes"のままではlikesテーブルを経由した後の参照先が不明。(like_postsはテーブル名ではなく独自に設定したメソッド名のようなもの?)
  # sourceオプションにより参照先のテーブルを明示することができる。
  # 'source: :post'としてあげれば、likesテーブルを経由しpostsテーブルのデータを取得してくることができる。

  # 〜〜なぜわざわざsourceオプションを使ってまでlike_postsという項目を作っているのか〜〜
  # 「userがいいねしたpostを取得したい」ということであれば、"has_many :posts, through: :likes"でも良いように一見考えられるが、
  # userとpostの間には既にアソシエーションが組まれており、そこに新たな関係性を追加することはできないためlike_postsという項目を設定する必要がある。

  # 【フォロー機能に関するアソシエーション】
  # userとrelationshipについてアソシエーションを組む必要がある。簡潔に"has_many :relationships"としたい所だが、
  # relationshipテーブルに２つあるカラムはどちらもuserテーブルに紐づく中間テーブルとなっており、どちらのカラムとのアソシエーションなのかをしっかり区別してあげる必要がある。
  # よって、以下２パターンのアソシエーションを記述するということになる。
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # "User"とRelationshipテーブルの「follower_id」とのアソシエーションを設定している。
  # active_relationshipsと命名しているため、class_nameでテーブル名を明示。かつforeign_key設定により参照するカラムも指定。
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # 上と同じ。

  # ActiveRecordの関連付け。correctionを取得する。
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # "User"が「フォローをしている相手」および「フォローを受けている相手」を取得できるようにするための記述。
  # 上記で設定した"〜〜〜_relationships"を経由し、sourceを持つuserを関連付ける。
  # user.followingを実行する→→"active_relationships"を経由する(userは自身のidを元にRelationテーブル/follower_idを参照)→→sourceオプションにより、idが一致したレコードのデータを取得できる
  # 要は関連付けされたコレクションを取得できるよってこと。

  # 【いいね機能に関するメソッド】
  # 主にhas_many関連付けをしたコレクションメソッド"like_posts"を使用する。"self"は省略されている。
  def like(post)
    like_posts << post
    # current_userが持つ"like_posts"に、コントローラーより受け取った"postオブジェクト(いいねしようとしている投稿)"をいいねするたびに格納していくという処理。
    # <<はRubyのArrayクラスのインスタンスメソッド。pushでもいいかも。
    # あまりRubyっぽくないが次のように書き換えも可。
    # self.like_posts.push(post)※もしやこっちの方がわかりやすいのでは・・・
  end

  def unlike(post)
    like_posts.destroy(post)
    # current_userが持つ"like_posts"に格納されているpost(コントローラーから受け取ったpost)を削除する。
  end

  def like?(post)
    like_posts.include?(post)
    # current_userが持つ"like_posts"にview(_like_area)より受け取った"postオブジェクト"が格納されているかどうかを確認する。
    # like_postsが、postと等しい要素を持つ時にtrue、持たない時にfalseを返す。
  end

  # 【フォロー機能に関するメソッド】
  # 上記"いいね機能"とほぼ同じロジックを用いている。
  def follow(other_user)
    following << other_user
    # current_userが持つ"following"に、コントローラーより受け取った"other_userオブジェクト(@userのこと)"をフォローするたびに格納していくという処理。
    # <<はRubyのArrayクラスのインスタンスメソッド。
    # 書き換えも可。→ self.following.push(other_user)
  end

  def unfollow(other_user)
    following.destroy(other_user)
    # current_userが持つ"following"に格納されているother_user(コントローラーから受け取った@user)を削除する。
  end

  def following?(other_user)
    following.include?(other_user)
    # current_userが持つ"following"にview(_follow_area)より受け取った"userオブジェクト"が格納されているかどうかを確認する。
    # followingが、userと等しい要素を持つ時にtrue、持たない時にfalseを返す。
  end

  def feed
    Post.where(user_id: following_ids << id)
    # postの中から、post.user_idが条件に一致するものを探す。
    # whereは条件に合うレコードを全て返す処理を行う。
    # whereの中身はハッシュである。キー：user_id、値：following_ids << id
    # 値：following_ids << idは次のように書き換えできる。 self.following_ids.push(self.id)
    # following_idsは、ActiveRecordのcollection_singular_idsメソッド。Railsガイド4.3.1.7参照
    # 要するに、following_idsメソッドに自分のuser.idを加えたものを戻り値として返すということ。
  end

  scope :recent, ->(count) { order(created_at: :desc).limit(count) }
  # 作成順での並び替え。(count)で数字を引数として受け取れる。

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user) # 新規登録された@userでそのままログインする
      redirect_to posts_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/users/_follow.html.slim
= link_to relationships_path(followed_id: user.id), class: 'btn btn-raised btn-outline-warning', method: :post, remote: true do
  | フォロー

/ フォローをするというリンクになるので、relationshipsコントローラーのcreateアクションにデータを送ってあげる必要がある。
/ コントローラーcreateでは、"@user = User.find(params[:followed_id])"と記述している。つまり、今クリックしようとしているuserのidが分かれば良い。
/ なので現在持っている@userのidをfollowed_idとして渡してあげる。

app/views/users/_follow_area.html.slim
- if logged_in? && current_user.id != user.id
  / ログインしている かつ 表示しているユーザーがログインしているユーザーではない場合、以下を表示
  div id="follow-area-#{user.id}"
    - if current_user.following?(user)
      = render 'users/unfollow', user: user
    - else
      = render 'users/follow', user: user

/ user.rbにて設定しているfollowing?メソッドを実行している。戻り値はtrue/false
/ posts/index → users/_user から@userをuserとして受け取っている

app/views/users/_unfollow.html.slim
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-warning btn-raised', method: :delete, remote: true do
  | アンフォロー

/ フォローを外すというリンクになるので、relationshipsコントローラーのdestroyアクションにデータを送ってあげる必要がある。
/ コントローラーdestoryでは、"@user = Relationship.find(params[:id]).followed"と記述している。
/ 上記を満たすために、コントローラー側ではRelationshipテーブルで現在削除しようとしているレコードの情報(params)が必要となる。
/ よって、/relationships?id=○○のような形で渡してあげたい（クエリの知識が浅く、果たして合っているか怪しい・・・）
/ 次のようにクエリが実行される。→→active_relationshipsは自身のidを元にRelationテーブル/follower_idを参照。
/ →→さらにfindメソッドでfollowed_idカラムから@userオブジェクトのidを検索。そのデータをRelationship(params)として渡す。

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.username
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          = render @users
    .col-md-6.col-12.offset-md-3
      = paginate @users

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        
        .form-group
          = f.label :username, class: 'bmd-label-floating'
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary' 

app/views/users/show.html.slim
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          - if logged_in? && current_user.id == @user.id
            / 未ログインの場合は短絡評価が適用されるのでcurrent_user=>nilによるエラーにはならない。
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '100x100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.username
          .text-center
            = render 'follow_area', user: @user
          hr
          .row
            = render partial: 'posts/thumbnail_post', collection: @user.posts
            / showページが所持している@user.postsを"posts/thumbnail_post"へ渡す