config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users, only: %i[index new create show]
  resources :posts do
    collection do
      get 'search'
      # ネストすることでpostsコントローラーのsearchアクションを取得する。
      # collectionによりposts全体を対象としているため、idを必要としないパスとなる。
    end
    resources :comments, shallow: true
  end
  # shallowオプションについてはRailsガイド'ルーティング'の2.7.2を参考に記述
  # comment_idをparamsに持つアクション(show/edit/update/destroy)についてURLを短くすることができる。
  # (urlを短くしても一意性を確保出来ている)

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  namespace :mypage do
    resource :account, only: %i[edit update]
  end
  # namespaceでコントローラーをグループ化する。(今はaccountsコントローラーのみだが、今後増えることを想定した実装となる)
  # この記述で、/"namespace名"/"コントローラー名"というパスを得る。
  # 自分自身に対しての処理のため単一resourceメソッドを用いた。

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'Flipgram', root_path, class: 'navbar-brand'
  / トグルメニューの記載
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    / 以下はアイコン
    span.navbar-toggler-icon

  #navbarTogglerDemo02.collapse.navbar-collapse
    / 上記で以下の要素をトグルに入れる
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to '投稿一覧', posts_path, class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_error_messages.html.slim
- if object.errors.any? #実行中のオブジェクトにエラーがあるかどうか
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg| #全てのエラーメッセージを取り出してlistで表示
        li = msg 

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'Flipgram', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    / 以下の要素をトグルメニューに入れる
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
         = link_to '投稿一覧', posts_path, class: 'nav-link'
      li.nav-item
         = link_to '新規投稿', new_post_path, class: 'nav-link'
      li.nav-item
        = link_to current_user.username, user_path(current_user), class: 'nav-link'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete 

app/views/shared/_modal.html.slim
#modal-container

/ モーダルに部分テンプレートとしてIDを設定している
/ 今後コメント以外にもモーダルを使用したい時に、JSでここにhtmlを挿入することで表示内容を変更することができる。