config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users, only: %i[index new create show]
  resources :posts do
    collection do
      get 'search'
      # ネストすることでpostsコントローラーのsearchアクションを取得する。
      # collectionによりposts全体を対象としているため、idを必要としないパスとなる。
    end
    resources :comments, shallow: true
  end
  # shallowオプションについてはRailsガイド'ルーティング'の2.7.2を参考に記述
  # comment_idをparamsに持つアクション(show/edit/update/destroy)についてURLを短くすることができる。
  # (urlを短くしても一意性を確保出来ている)

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  namespace :mypage do
    resource :account, only: %i[edit update]
  end
  # namespaceでコントローラーをグループ化する。(今はaccountsコントローラーのみだが、今後増えることを想定した実装となる)
  # この記述で、/"namespace名"/"コントローラー名"というパスを得る。
  # 自分自身に対しての処理のため単一resourceメソッドを用いた。

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  # uploaderファイルをimageカラムに適用
  # 今後複数画像を取り扱うことになった場合はuploaders:imagesと複数形にする

  # serialize :images, JSON
  # carrierwaveで複数画像を保存する場合はJSON型で扱う必要がある。
  # DBをJSON型で設定していないケースでは、modelにて設定する。

  belongs_to :user
  # postは１つのuserを持つ、というアソシエーション
  # この記載がないと、参照先(この場合はuser)テーブルにアクセスできない

  has_many :comments, dependent: :destroy
  # postは複数のcommentを持つ
  # dependent: :destroyについてはuserモデルに記述済

  has_many :likes, dependent: :destroy
  # ↓いいねをしたuserを取得するための記述
  has_many :like_users, through: :likes, source: :user
  # 内容についてはuser.rbと重複するので割愛

  scope :body_contain, ->(word) { where('body LIKE ?', "%#{word}%") }
  # 検索のロジックを記述。検索フォームに入力されたものを第2引数である、"->(word) { where('body LIKE ?', "%#{word}%") }" を実行し、値を返す。
  # （SearchPostsFormインスタンスのself.bodyを受け取っている）
  # プレースホルダーを用い、SQLインジェクションを回避。

  validates :body, presence: true, length: { maximum: 255 }
  validates :image, presence: true
  # migrationファイルでnullfalseをつけたものはこちらでもバリデーションをつける。
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]
  # require_loginメソッドにより、ログインしていないユーザは上記５つのアクションを実行できない

  def index
    # includesがないとuser_idについてsqlが多量発行される（N+1問題の解消）
    # orderはrailsのActiveRecordメソッドのひとつ。()内記述で並び順を変更できる。descは降順
    # .page(params[:page])により現在のページパラメーターを受け取っている
    # kaminariのデフォルト設定により最初のページはparamsを無視する（config.params_on_first_page = false）
    @posts = if current_user
               # ログイン中であれば、ログインしているユーザーがフォローしている人の投稿のみ表示される分岐
               current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
             # feedはuser.rbにて設定。フォロー済ユーザー+自分のPostを取り出すメソッド。
             else
               Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
               # 非ログイン時は全ての投稿を表示。
             end
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
    # 他人が編集ページに遷移できなくするためにcurrent_userをつけている。
    # 上記を設定しないと/posts/:id/editのid部分を変えたら入れてしまう。
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, success: '投稿を更新しました'
    else
      flash.now[:danger] = '投稿の更新に失敗しました'
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    # 投稿詳細ページでコメントを表示させるための記述。@postに紐づくコメントを@commentに入れる
    # 一覧ページと同じで、N+1対策と並び順
    @comment = Comment.new
    # commentsコントローラーのcreateにアクションを実行するために、インスタンスを生成
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_to posts_path, success: '投稿を削除しました'
    else
      # 万が一削除に失敗した場合はフラッシュを表示し、直前ページに戻る仕様にした。
      # （削除場所がindexページとshowページの2パターンあるため）
      flash.now[:danger] = '投稿の削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
    # application_controllerで定義した@search_formについて検索をかける。
    # includes(:user)はN+1問題対応。検索はPostについてだが、それに紐づくUserについてもSQLが発行されてしまう。
  end

  private

  def post_params
    params.require(:post).permit(:body, :image).merge(user_id: current_user.id)
  end
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|
  = render 'shared/error_messages', object: post
  .form-group
    - if post.image?
      = f.label :image
      = f.file_field :image, accept: 'image/*', onchange: 'previewFileWithId(preview)', class: 'form-control'
      = image_tag post.image.url, id: 'preview', size: '300x300', class: 'image-thumbnail'
    - else
      = f.label :image
      = f.file_field :image, accept: 'image/*', onchange: 'previewFileWithId(preview)', class: 'form-control'
      = image_tag 'no-image.png', id: 'preview', size: '300x300', class: 'image-thumbnail'

  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'

  = f.submit class: 'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
= link_to likes_path(post_id: post.id), method: :post, remote: true do
  = icon 'far', 'heart', class: 'fa-lg'

/ like_areaにていいねされていないの投稿である場合の表示。
/ 色が塗られていないハートが表示されていて、ボタンを押すといいねをする(post)という処理をリクエストする。
/ コントローラーに"どの投稿にいいねしたのか"という情報を渡せるように"link_to likes_path(post_id: post.id)"と記述している。
/ このように記述すると、/likes?post_id=1 のようにクエリとして渡してあげるできる。

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    = render 'unlike', post: post
  - else
    = render 'like', post: post
  / user.rbにて設定しているlike?メソッドを実行している。

app/views/posts/_post.html.slim
.card.mb-5.post
  / mb-5でcardごとに下側のmarginを付与している
  .card-header
    .d-flex.align-items-center
      = link_to user_path(post.user) do
        = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = post.user.username

      / ログイン時かつ自身の投稿の場合は編集削除ができる分岐を導入する
      - if logged_in? && post.user_id == current_user.id
        .ml-auto
          = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'

      / ログイン時かつ自身の投稿でない場合は"いいね"ができる分岐を導入する
      - if logged_in? && post.user_id != current_user.id
        .ml-auto
          = render 'like_area', post: post

  = link_to post_path(post) do
    / swiperの公式ページ見本に沿って記述
    .swiper-container
      .swiper-wrapper
        / / 変数postにある配列imagesを一つずつ取り出す
        / - post.images.each do |image|
        .swiper-slide
          = image_tag post.image.url, class: 'card-img-top'
      .swiper-pagination

  .card-body
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
= form_with model: search_form, url: search_posts_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  = f.search_field :body, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

/ "model: search_form"で格納するインスタンスの指定(viewから@search_formを受け取っている)
/ "url: search_posts_path"で送信先をpostsコントローラーのsearchアクションにしている。

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3
  = link_to post_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.image.url
/ users/showからthumbnail_post(user.postのこと)を受け取っている。

app/views/posts/_unlike.html.slim
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

/ like_areaにていいね済みの投稿である場合の表示。
/ 色ぬりのハートが表示されていて、ボタンを押すといいねを外す(delete)という処理をリクエストする。
/ 受け取っている変数postの中身を元にlike_pathを割り出す(likesの中からpost_idを持つlikeを探している)

app/views/posts/edit.html.slim
.container
  .row.justify-content-center
    .col-md-6.col-12
      .card
        .card-body
          / 部分テンプレート先のファイル名を'form'で指定している
          = render 'form', post: @post

app/views/posts/index.html.slim
.container
  .row
    .col-md-8.col-12
      / @postsに入っているデータ分、render以下の表示を繰り返す
      / pertialとcollectionを省略した記法
      / 部分テンプレート先には@posts→変数postとして代入される
      / postの有無で分岐
      - if @posts.present?
        = render @posts
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      = paginate @posts

    / 画面右側はユーザー情報を載せる記述
    .col-md-4.col-12
      / ログインがtrueならば表示。logged_in?はsoceryのメソッド。
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1'
          = link_to current_user.username, user_path(current_user)

      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            = render @users
          .card-footer
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          / 部分テンプレート名を指定する場合は以下の書き方になる
          = render 'form', post: @post

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        / - @post.images.each do |image|
        .swiper-slide
          = image_tag @post.image.url
      .swiper-pagination

  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        / ログイン時かつ自身の投稿の場合は編集削除ができる分岐を導入する
        - if logged_in? && @post.user_id == current_user.id
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'

        / ログイン時かつ自身の投稿でない場合は"いいね"ができる分岐を導入する
        - if logged_in? && @post.user_id != current_user.id
          .ml-auto
            = render 'like_area', post: @post

    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          / railsのsimple_formatメソッドを使用し、入力時の改行等を反映できるようにする
          = simple_format(@post.body)
      hr
      / コメント一覧
      = render 'comments/comments', comments: @comments

    - if logged_in?
      / 非ログイン時にフォーム非表示。
      hr.m-0
      .post-comment.p-3
        / 新規コメント投稿フォーム
        = form_with model: [@post, @comment], class: 'd-flex mb-0 flex-nowrap justify-content-between', remote: true do |f|
          = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
          = f.submit '投稿', class: 'btn btn-primary btn-raised'
          / modelを[@post, @comment]と指定することで、formの送信先がcommentコントローラーのcreateアクションとなる(showページ内の場合)
          / remote: true という記述はjs形式でリクエストを送信するためのもの。非同期対応
    - else
      / 非ログイン時にはフォームの代わりに以下の案内を表示
      .post-comment.p-3
        | ※コメント投稿にはログインが必要です